### ISSUE TITLE
The "Get Ticket" user story does not work

### ISSUE THREAD

**Issue by emanuelefrisi** [lorericci/SE2-Group-15---Office-Queue-#3]
The current implementation of the "Get Ticket" user story is not functioning correctly. This is because the backend logic is not utilizing the database to handle ticket issue

**Comment by umberto-fontanazza** [comment]
The ticketId is taken from the id series of the db. The services and counters config are not taken from the db currently because the story "CONFIG COUNTERS" is not planned for this sprint. 

Did you have troubles in getting the ticketId from the db as well?

**Comment by emanuelefrisi** [comment]
No troubles
